#!/usr/bin/env python3

import re
from sys import argv

value_pat = re.compile('^ *([^=]+) *= *(.*) *$')

known = {}
f2 = open(argv[2])
for ll in f2:
    l = ll.replace('\n', '')
    m = re.match(value_pat, l)
    if not m:
        continue
    known[m.group(1).strip()] = m.group(2).strip()
f2.close()

f1 = open(argv[1])
for ll in f1:
    l = ll.replace('\n', '')
    m = re.match(value_pat, l)
    if not m:
        print('')
        continue
    name = m.group(1).strip()
    value = m.group(2).strip()
    if name in known:
        print(name + ' = ' + known[name])
        continue
    print(name + ' = ' + value)
