#!/bin/bash -e

THIS=${0##*/}

[ -z "$1" ] && echo "$THIS:no lang to check given" && exit 1

ORIG_FILE=../ru/src/main/resources/org/luwrain/i18n/ru/constants.properties
CHECKING_FILE=../$1/src/main/resources/org/luwrain/i18n/$1/constants.properties

while read l;do
L=${l%%=*}
L="$(echo $L)"
if ! grep -q "$L" "$CHECKING_FILE"; then
echo "#$l"
fi
done  < "$ORIG_FILE"
